dist: trusty
sudo: required
install:
  - source ./support/install_texlive.sh
  - source ./support/install_fira.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - /tmp/fonts
script:
  # Prefix command with travis_wait x so it times out after 3 mins
  - mkdir build
  - cd src
  - travis_wait 5 pdflatex -output-directory ../build ./limecv.dtx
  - travis_wait 5 pdflatex -output-directory ../build ./limecv.ins
  - cd ..
  - cp build/limecv.cls examples/
  - cd examples
  - travis_wait 5 pdflatex mwe-latex.tex
  - travis_wait 5 xelatex mwe-xelatex.tex
  #- travis_wait 5 lualatex mwe-lualatex.tex
